config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :sessions, only: [:new, :create, :destroy]
  resources :events, only: [:new, :create, :index, :show]
  root "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attend.rb
class Attend < ApplicationRecord
    belongs_to :attended_event, class_name: "Event"
    belongs_to :attendee, class_name: "User"
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User"
    has_many :attends, foreign_key: "attended_event_id"
    has_many :attendees, through: :attends, source: :attendee
    scope :future, -> { where("date >= ?", Date.today) }
    scope :past, -> { where("date < ?", Date.today) }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :events, foreign_key: "creator_id", class_name: "Event", dependent: :destroy
    has_many :attends, foreign_key: "attendee_id"
    has_many :attended_events, through: :attends, source: :attended_event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    helper_method :logged_in?
    
    def current_user
        User.find_by(id: session[:current_user_id])
    end

    def logged_in?
        !current_user.nil?
    end

    def authenticate_user!
        if logged_in?

        else
            redirect_to new_sessions_path
        end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, :only => [:new]
    def index
        @events = Event.all
        @prev_events = Event.past
        @upcoming_events = Event.future
    end

    def new
        @event = Event.new
    end

    def create
        @event = current_user.events.build(event_params)

        if @event.save
            redirect_to @event
        else
            render :new
        end
    end

    def show
        @event = Event.find(params[:id])
        @attendees = @event.attendees.all
    end

    private
    def event_params
        params.require(:event).permit(:description, :date)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by_name(params[:name])
        if user != nil
            session[:current_user_id] = user.id
            session[:current_user_name] = user.name
            flash[:success] = "User logged in"
            redirect_to user_path(user)
        else
            render :new
        end
    end

    def destroy
        session[:current_user_id] = nil
        session[:current_user_name] = nil
        flash[:success] = "Logged out"
        redirect_to new_sessions_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            redirect_to @user
            session[:current_user_id] = @user.id
            session[:current_user_name] = @user.name
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
        @events = @user.events
        @attendeds = @user.attended_events.all
    end

    private
    def user_params
        params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<ul>
    <h1>Upcoming Events</h1>
    <% @upcoming_events.each do |event| %>
        <li>
            <%= link_to event.description, event%>
        </li>
    <% end %>
</ul>
<ul>
    <h1>Past Events</h1>
    <% @prev_events.each do |event| %>
        <li>
            <%= link_to event.description, event%>
        </li>
    <% end %>
</ul>

app/views/events/new.html.erb
<%= form_with model: @event do |f| %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.label :date %>
    <%= f.date_field :date %>
    <%= f.submit "Submit" %>
<% end %>

app/views/events/show.html.erb
<%= @event.description %>
<%= @event.creator.name %>
<ul>
    <% @attendees.each do |attendee| %>
        <li>
            <%= attendee.name %>
        </li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>
    <% if session[:current_user_id] %>
        <%= session[:current_user_name] %>
        <%= link_to "Log out", sessions_path, method: :delete %>
        <%= link_to "Make Event", new_event_path %>
        <%= link_to "All Events", events_path %>
    <% else %>
        <%= link_to "Log in", new_sessions_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_with model: @user do |f| %>
    <%= f.label :name%>
    <%= f.text_field :name %>
    <%= f.submit "Submit" %>
<% end %>

app/views/users/show.html.erb
<%= @user.name %>
<ul>
    <% @events.each do |event| %>
        <li>
            <%= event.description%>
        </li>
    <% end %>
</ul>
<ul>
    <% @attendeds.each do |attended| %>
        <% if attended.date.past? %>
        <li>
            Past Event
            <%= attended.description %>
        </li>
        <% else %>
        <li>
            Upcoming Event
            <%= attended.description %>
        </li>
        <% end %>
    <% end %>
</ul>